_wandb:
    value:
        cli_version: 0.23.1
        e:
            u519n0uxhevfvn7q9wadjpaag004cf5n:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "11811160064"
                codePath: train_wandb.py
                codePathLocal: train_wandb.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "184665743360"
                email: st0490@princeton.edu
                executable: /Users/phucta/envs/cos461/bin/python3
                git:
                    commit: ed9c32c92b1810332c82b493f2916ea3f127adcf
                    remote: https://github.com/phucta0405/QML_ece396.git
                host: dynamic-oit-ip4-wifirestricted03-10-48-140-7.princeton.edu
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/phucta/QML_ece396/train_wandb.py
                python: CPython 3.11.14
                root: /Users/phucta/QML_ece396
                startedAt: "2025-12-15T20:09:20.236570Z"
                writerId: u519n0uxhevfvn7q9wadjpaag004cf5n
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
max_dim:
    value: 14
min_dim:
    value: 2
model:
    value: transformer
n_runs:
    value: 1
num_samples:
    value: 1000
step:
    value: 1
sweep_type:
    value: nsphere_dim
